// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myproto.proto

package io.grpc.myproto;

/**
 * Protobuf type {@code myproto.addExerciseR}
 */
public  final class addExerciseR extends
    com.google.protobuf.GeneratedMessageLite<
        addExerciseR, addExerciseR.Builder> implements
    // @@protoc_insertion_point(message_implements:myproto.addExerciseR)
    addExerciseROrBuilder {
  private addExerciseR() {
    t1_ = "";
    t2_ = "";
    sBinary_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }
  /**
   * <code>optional int32 id = 1;</code>
   */
  private void setId(int value) {
    
    id_ = value;
  }
  /**
   * <code>optional int32 id = 1;</code>
   */
  private void clearId() {
    
    id_ = 0;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>optional int32 type = 2;</code>
   */
  public int getType() {
    return type_;
  }
  /**
   * <code>optional int32 type = 2;</code>
   */
  private void setType(int value) {
    
    type_ = value;
  }
  /**
   * <code>optional int32 type = 2;</code>
   */
  private void clearType() {
    
    type_ = 0;
  }

  public static final int T1_FIELD_NUMBER = 3;
  private java.lang.String t1_;
  /**
   * <code>optional string T1 = 3;</code>
   */
  public java.lang.String getT1() {
    return t1_;
  }
  /**
   * <code>optional string T1 = 3;</code>
   */
  public com.google.protobuf.ByteString
      getT1Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(t1_);
  }
  /**
   * <code>optional string T1 = 3;</code>
   */
  private void setT1(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    t1_ = value;
  }
  /**
   * <code>optional string T1 = 3;</code>
   */
  private void clearT1() {
    
    t1_ = getDefaultInstance().getT1();
  }
  /**
   * <code>optional string T1 = 3;</code>
   */
  private void setT1Bytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    t1_ = value.toStringUtf8();
  }

  public static final int T2_FIELD_NUMBER = 4;
  private java.lang.String t2_;
  /**
   * <code>optional string T2 = 4;</code>
   */
  public java.lang.String getT2() {
    return t2_;
  }
  /**
   * <code>optional string T2 = 4;</code>
   */
  public com.google.protobuf.ByteString
      getT2Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(t2_);
  }
  /**
   * <code>optional string T2 = 4;</code>
   */
  private void setT2(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    t2_ = value;
  }
  /**
   * <code>optional string T2 = 4;</code>
   */
  private void clearT2() {
    
    t2_ = getDefaultInstance().getT2();
  }
  /**
   * <code>optional string T2 = 4;</code>
   */
  private void setT2Bytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    t2_ = value.toStringUtf8();
  }

  public static final int SBINARY_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString sBinary_;
  /**
   * <code>optional bytes sBinary = 5;</code>
   */
  public com.google.protobuf.ByteString getSBinary() {
    return sBinary_;
  }
  /**
   * <code>optional bytes sBinary = 5;</code>
   */
  private void setSBinary(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    sBinary_ = value;
  }
  /**
   * <code>optional bytes sBinary = 5;</code>
   */
  private void clearSBinary() {
    
    sBinary_ = getDefaultInstance().getSBinary();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (type_ != 0) {
      output.writeInt32(2, type_);
    }
    if (!t1_.isEmpty()) {
      output.writeString(3, getT1());
    }
    if (!t2_.isEmpty()) {
      output.writeString(4, getT2());
    }
    if (!sBinary_.isEmpty()) {
      output.writeBytes(5, sBinary_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, type_);
    }
    if (!t1_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getT1());
    }
    if (!t2_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getT2());
    }
    if (!sBinary_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, sBinary_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static io.grpc.myproto.addExerciseR parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.grpc.myproto.addExerciseR parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.grpc.myproto.addExerciseR parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.grpc.myproto.addExerciseR parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.myproto.addExerciseR prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code myproto.addExerciseR}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.grpc.myproto.addExerciseR, Builder> implements
      // @@protoc_insertion_point(builder_implements:myproto.addExerciseR)
      io.grpc.myproto.addExerciseROrBuilder {
    // Construct using io.grpc.myproto.addExerciseR.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional int32 type = 2;</code>
     */
    public int getType() {
      return instance.getType();
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public Builder setType(int value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <code>optional int32 type = 2;</code>
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    /**
     * <code>optional string T1 = 3;</code>
     */
    public java.lang.String getT1() {
      return instance.getT1();
    }
    /**
     * <code>optional string T1 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getT1Bytes() {
      return instance.getT1Bytes();
    }
    /**
     * <code>optional string T1 = 3;</code>
     */
    public Builder setT1(
        java.lang.String value) {
      copyOnWrite();
      instance.setT1(value);
      return this;
    }
    /**
     * <code>optional string T1 = 3;</code>
     */
    public Builder clearT1() {
      copyOnWrite();
      instance.clearT1();
      return this;
    }
    /**
     * <code>optional string T1 = 3;</code>
     */
    public Builder setT1Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setT1Bytes(value);
      return this;
    }

    /**
     * <code>optional string T2 = 4;</code>
     */
    public java.lang.String getT2() {
      return instance.getT2();
    }
    /**
     * <code>optional string T2 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getT2Bytes() {
      return instance.getT2Bytes();
    }
    /**
     * <code>optional string T2 = 4;</code>
     */
    public Builder setT2(
        java.lang.String value) {
      copyOnWrite();
      instance.setT2(value);
      return this;
    }
    /**
     * <code>optional string T2 = 4;</code>
     */
    public Builder clearT2() {
      copyOnWrite();
      instance.clearT2();
      return this;
    }
    /**
     * <code>optional string T2 = 4;</code>
     */
    public Builder setT2Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setT2Bytes(value);
      return this;
    }

    /**
     * <code>optional bytes sBinary = 5;</code>
     */
    public com.google.protobuf.ByteString getSBinary() {
      return instance.getSBinary();
    }
    /**
     * <code>optional bytes sBinary = 5;</code>
     */
    public Builder setSBinary(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSBinary(value);
      return this;
    }
    /**
     * <code>optional bytes sBinary = 5;</code>
     */
    public Builder clearSBinary() {
      copyOnWrite();
      instance.clearSBinary();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:myproto.addExerciseR)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.grpc.myproto.addExerciseR();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        io.grpc.myproto.addExerciseR other = (io.grpc.myproto.addExerciseR) arg1;
        id_ = visitor.visitInt(id_ != 0, id_,
            other.id_ != 0, other.id_);
        type_ = visitor.visitInt(type_ != 0, type_,
            other.type_ != 0, other.type_);
        t1_ = visitor.visitString(!t1_.isEmpty(), t1_,
            !other.t1_.isEmpty(), other.t1_);
        t2_ = visitor.visitString(!t2_.isEmpty(), t2_,
            !other.t2_.isEmpty(), other.t2_);
        sBinary_ = visitor.visitByteString(sBinary_ != com.google.protobuf.ByteString.EMPTY, sBinary_,
            other.sBinary_ != com.google.protobuf.ByteString.EMPTY, other.sBinary_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                type_ = input.readInt32();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                t1_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                t2_ = s;
                break;
              }
              case 42: {

                sBinary_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (io.grpc.myproto.addExerciseR.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:myproto.addExerciseR)
  private static final io.grpc.myproto.addExerciseR DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new addExerciseR();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static io.grpc.myproto.addExerciseR getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<addExerciseR> PARSER;

  public static com.google.protobuf.Parser<addExerciseR> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

