// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myproto.proto

package io.grpc.myproto;

public interface addExerciseROrBuilder extends
    // @@protoc_insertion_point(interface_extends:myproto.addExerciseR)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional int32 type = 2;</code>
   */
  int getType();

  /**
   * <code>optional string T1 = 3;</code>
   */
  java.lang.String getT1();
  /**
   * <code>optional string T1 = 3;</code>
   */
  com.google.protobuf.ByteString
      getT1Bytes();

  /**
   * <code>optional string T2 = 4;</code>
   */
  java.lang.String getT2();
  /**
   * <code>optional string T2 = 4;</code>
   */
  com.google.protobuf.ByteString
      getT2Bytes();

  /**
   * <code>optional bytes sBinary = 5;</code>
   */
  com.google.protobuf.ByteString getSBinary();
}
