// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myproto.proto

package io.grpc.myproto;

public interface addLessonAOrBuilder extends
    // @@protoc_insertion_point(interface_extends:myproto.addLessonA)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string ok = 1;</code>
   */
  java.lang.String getOk();
  /**
   * <code>optional string ok = 1;</code>
   */
  com.google.protobuf.ByteString
      getOkBytes();
}
