// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myproto.proto

package io.grpc.myproto;

public interface getExerciseROrBuilder extends
    // @@protoc_insertion_point(interface_extends:myproto.getExerciseR)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();
}
